### PR TITLE
Do case insensitive comparison in lock_manager.yaml

### PR DESCRIPTION
**Pull request by mew1033**
unknown != Unknown

### CODE REVIEW

**Review by firstof9 — APPROVED** [review]
This change will be good until I update the sensor.py with the revised text.

**Comment by firstof9** [comment]
@FutureTense if you want to, you can cherry pick this commit: https://github.com/firstof9/lock-manager/commit/3a9e57902d69bc94d0218a1c040d14517e2d35b0 to fix this

**Comment by mew1033** [comment]
This PR makes the comparison work with both cases, but as long as its consistent, it shouldn't matter too much.

**Comment by firstof9** [comment]
Ya I was waiting for some testing, but I'll have a PR to change the case, that's @mew1033 for catching this tho.

**Pull request closed without merging**
